on:
  create:
    branches:
      - master

name: Initialize this repository

jobs:
  job1:
    name: do the job plz
    runs-on: ubuntu-latest
    steps:
      - id: step10
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - id: step20
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          node ./scripts/init.js ${{ github.repository_owner }} ${{ github.repository }}
          git commit -m "Tailoring your package.json"
          git push origin master

