on:
  workflow_dispatch:

name: Initialize an AppSync Project

jobs:
  init-pkg:
    name: Repository Initialization
    runs-on: ubuntu-latest
    env:  
      COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
      COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
      COMMIT_USER_PAT: ${{ secrets.COMMIT_USER_PAT }}
    steps:
      - id: step10
        name: Checkout Code
        uses: actions/checkout@v2
        with:
        # This same token will be used later for "git push" and other authenticated commands
          token: ${{ env.COMMIT_USER_PAT }}
          ref: 'master'
      - id: step20
        name: Update package.json
        run: |
          yarn
          node ./.centaur/scripts/init.js \
            initPkg \
            ${{ github.repository_owner }} \
            ${{ github.repository }}
      - id: step25
        name: Try commit package.json
        env:
          COMMIT_MESSAGE: Tailored package.json
        run: |
          git config user.name ${{ env.COMMIT_USER_NAME }}
          git config user.email ${{ env.COMMIT_USER_EMAIL }}
          ./.centaur/scripts/tryGitCommit.sh
          git push origin master
  init-amplify:
    needs: init-pkg
    name: Amplify Initialization
    runs-on: ubuntu-latest
    env:  
      COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
      COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
      COMMIT_USER_PAT: ${{ secrets.COMMIT_USER_PAT }}
      REGION: ap-south-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY_ID }}
      ENVNAME: dev
      CENTAUR_CACHE_PATH: ./.centaur/cache/init-workflow/${{ github.run_number }}
    steps:
      - id: step10
        name: Checkout Code
        uses: actions/checkout@v2
        with:
        # This same token will be used later for "git push" and other authenticated commands
          token: ${{ env.COMMIT_USER_PAT }}
          ref: 'master'        
      - id: step20
        name: Prepare headless params
        run: |
          mkdir -p ${{ env.CENTAUR_CACHE_PATH }}
          yarn
          node ./.centaur/scripts/init.js \
            cacheHeadlessParams \
            amplifyInit \
            ${{ github.repository_owner }} \
            ${{ github.repository }} \
            ${{ github.run_number }} \
            ${{ env.REGION }} \
            ${{ env.AWS_ACCESS_KEY_ID }} \
            ${{ env.AWS_SECRET_ACCESS_KEY }} \
            ${{ env.ENVNAME }} \
            ${{ env.CENTAUR_CACHE_PATH }}
      - id: step30
        name: Do amplify init
        run: |
          sudo npm install -g @aws-amplify/cli
          ./.centaur/scripts/amplifyInit.sh
      - id: step40
        name: Cache amplify/team-provider-info.json
        uses: actions/cache@v2
        env:
          cache-name: team-provider
        with:
          # 
          path: ./amplify/team-provider-info.json
          key: environment-${{ env.ENVNAME }}-${{ env.cache-name }}
          restore-keys: |
            environment-${{ env.ENVNAME }}-${{ env.cache-name }}
      - id: step50
        name: Try commit amplify init changes
        env:
          COMMIT_MESSAGE: Done amplify init
        run: |
          git config user.name ${{ env.COMMIT_USER_NAME }}
          git config user.email ${{ env.COMMIT_USER_EMAIL }}        
          echo '# Override Amplify - ignore team-provider-info.json' >> .gitignore
          echo 'amplify/team-provider-info.json' >> .gitignore
          ./.centaur/scripts/tryGitCommit.sh
          git push origin master
      - id: step60
        name: Upload team-provider-info.json
        uses: actions/upload-artifact@v2
        with:
          name: team-provider-info-dev
          path: ./amplify/team-provider-info.json          
      - id: step70
        name: Cleanup
        run: |
          rm -Rf ${{ env.CENTAUR_CACHE_PATH }}
