on:
  workflow_dispatch:

name: Initialize an AppSync Project

jobs:
  init-repo:
    name: Repository Initialization
    runs-on: ubuntu-latest
    env:  
      COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
      COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
      COMMIT_USER_PAT: ${{ secrets.COMMIT_USER_PAT }}
    steps:
      - id: step10
        name: Checkout Code
        uses: actions/checkout@v2
        with:
        # This same token will be used later for "git push" and other authenticated commands
          token: ${{ env.COMMIT_USER_PAT }}
          ref: 'master'
      - id: step20
        name: Update package.json
        run: |
          git config user.name ${{ env.COMMIT_USER_NAME }}
          git config user.email ${{ env.COMMIT_USER_EMAIL }}
          node ./.template-scripts/init.js ${{ github.repository_owner }} ${{ github.repository }}
          git add .
          git commit -m "template: Tailoring your package.json"
          git push origin master

