on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

name: On PR (re)opened Workflow

jobs:
  amplify-env-add:
    name: Initialize a new amplify cloud environment
    runs-on: ubuntu-latest
    env:  
      COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
      COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
      COMMIT_USER_PAT: ${{ secrets.COMMIT_USER_PAT }}
      REGION: ap-south-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY_ID }}
      CENTAUR_CACHE_PATH: ./.centaur/cache/init-workflow/${{ github.run_number }}
      # env.ENVNAME is required but it must be randomly generated in this workflow, see step30
    steps:
      - id: step20
        name: Checkout Merge Branch Code
        uses: actions/checkout@v2
        with:
          # This same token will be used later for "git push" and other authenticated commands
          token: ${{ env.COMMIT_USER_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
      - id: step30
        name: Generate ENVNAME
        run: echo "::set-env name=ENVNAME::$(head /dev/urandom | tr -dc a-z | head -c 10 ;)"
      - id: step40
        name: Cache amplify/team-provider.json
        uses: actions/cache@v2
        env:
          cache-name: team-provider
        with:
          # This ensures that we dont have to manage persiting appId by ourselves. 
          # Also, the environment will be added to the same app as the 'dev' environment.
          # Versioning ./amplify/team-provider-info.json in git will be problematic with 
          # workflows that handle other "environments" - i.e. test, prod
          path: ./amplify/team-provider-info.json
          key: environment-dev-${{ env.cache-name }}
          restore-keys: |
            environment-dev-${{ env.cache-name }}
      - id: step50
        name: Prepare headless params
        run: |
          mkdir -p ${{ env.CENTAUR_CACHE_PATH }}
          yarn
          node ./.centaur/scripts/init.js \
            cacheHeadlessParams \
            amplifyEnvAdd \
            ${{ github.repository_owner }} \
            ${{ github.repository }} \
            ${{ github.run_number }} \
            ${{ env.REGION }} \
            ${{ env.AWS_ACCESS_KEY_ID }} \
            ${{ env.AWS_SECRET_ACCESS_KEY }} \
            ${{ env.ENVNAME }} \
            ${{ env.CENTAUR_CACHE_PATH }}
      - id: step60
        name: Do amplify env add
        run: |
          sudo npm install -g @aws-amplify/cli
          ./.centaur/scripts/amplifyEnvAdd.sh
      - id: step70
        name: Try commit amplify env add changes
        env:
          COMMIT_MESSAGE: Added new sandbox environment ${{ env.ENVNAME }}
        run: |
          git config user.name ${{ env.COMMIT_USER_NAME }}
          git config user.email ${{ env.COMMIT_USER_EMAIL }}        
          ./.centaur/scripts/tryGitCommit.sh
          git push 
      - id: step80
        name: Print App Details
        run: amplify status
      - id: step90
        name: Cleanup
        run: |
          rm -Rf ${{ env.CENTAUR_CACHE_PATH }}
