on:
  pull_request:
    types: [closed]
    branches:
      - master

name: On PR closed Workflow

jobs:
  amplify-env-del:
    name: Remove PR sandbox env from cloud
    runs-on: ubuntu-latest
    env:
      COMMIT_USER_EMAIL: ${{ secrets.COMMIT_USER_EMAIL }}
      COMMIT_USER_NAME: ${{ secrets.COMMIT_USER_NAME }}
      COMMIT_USER_PAT: ${{ secrets.COMMIT_USER_PAT }}
      REGION: ap-south-1
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY_ID }}
      CENTAUR_CACHE_PATH: ./.centaur/cache/init-workflow/${{ github.run_number }}
      # env.ENVNAME is required but it must be fetched from the workflow cache, see step40
    steps:
      - id: step20
        name: Checkout Merge Branch Code
        uses: actions/checkout@v2
        with:
          # This same token will be used later for "git push" and other authenticated commands
          token: ${{ env.COMMIT_USER_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
      - id: step30
        name: Fetch sandbox team-provider-info
        uses: actions/cache@v2
        env:
          cache-name: team-provider
        with:
          # This ensures that we dont have to manage persiting appId by ourselves.
          # Also, the environment will be added to the same app as the 'dev' environment.
          # Versioning ./amplify/team-provider-info.json in git will be problematic with
          # workflows that handle other "environments" - i.e. test, prod
          path: ./amplify/team-provider-info.json
          key: pr-${{ github.event.pull_request.number }}-${{ env.cache-name }}
          restore-keys: |
            pr-${{ github.event.pull_request.number }}-${{ env.cache-name }}
      - id: step40
        name: Fetch ENVNAME
        run: echo "::set-env name=ENVNAME::$(node ./.centaur/scripts/getCurrentEnv.js ./amplify/team-provider-info.json)"
      - id: step50
        name: Prepare headless params
        run: |
          mkdir -p ${{ env.CENTAUR_CACHE_PATH }}
          yarn
          node ./.centaur/scripts/init.js \
            cacheHeadlessParams \
            amplifyEnvRemove \
            ${{ github.repository_owner }} \
            ${{ github.repository }} \
            ${{ github.run_number }} \
            ${{ env.REGION }} \
            ${{ env.AWS_ACCESS_KEY_ID }} \
            ${{ env.AWS_SECRET_ACCESS_KEY }} \
            ${{ env.ENVNAME }} \
            ${{ env.CENTAUR_CACHE_PATH }}
      - id: step60
        name: Do amplify env remove
        run: |
          sudo npm install -g @aws-amplify/cli
          echo ${{ env.ENVNAME }}
          ./.centaur/scripts/amplifyEnvRemove.sh
      - id: step100
        name: Upload team-provider-info.json
        uses: actions/upload-artifact@v2
        with:
          name: team-provider-info-pr-${{ github.event.pull_request.number }}
          path: ./amplify/team-provider-info.json
